Models/ErrorViewModel.cs
namespace LearnosityDotNetExample.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using LearnosityDotNetExample.Models;

namespace LearnosityDotNetExample.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/LearnosityController.cs

using LearnositySDK.Request;
using LearnositySDK.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration.UserSecrets;


namespace LearnosityDotNetExample.Controllers
{
public class LearnosityController: Controller
{
        //public consumer key and secret that work for our public demos itembank found at https://demos.learnosity.com
        private readonly string consumerKey = "yis0TYCu7U9V4o7M";
        private readonly string secret = "74c5fd430cf1242a527f6223aebd42d30464be22";
        private readonly string domain;  

        public LearnosityController()
        {
            domain = "localhost";
        }

        public ActionResult Items()
        {
            JsonObject security = new JsonObject();
            security.set("consumer_key", consumerKey);
            security.set("domain", domain);

            JsonObject request = new JsonObject();
            request.set("mode", "item_list"); //https://reference.learnosity.com/author-api/initialization/mode

            JsonObject user = new JsonObject(); //Info for the user that is authoring items, saved as meta data
            user.set("id","Brad-Hunt-User-ID");
            user.set("firstname","Brad");
            user.set("lastname","Hunt");
            user.set("email","Brad.Hunt@learnosity.com");
            
            request.set("user",user);


            Init init = new Init("author", security, secret, request);
            ViewBag.SignedRequest = init.generate();
            return View();
        }
         public ActionResult Activities()
        {
            JsonObject security = new JsonObject();
            security.set("consumer_key", consumerKey);
            security.set("domain", domain);

            JsonObject request = new JsonObject();
            request.set("mode", "activity_list"); //https://reference.learnosity.com/author-api/initialization/mode

            JsonObject user = new JsonObject();
            user.set("id","Brad-Hunt-User-ID");
            user.set("firstname","Brad");
            user.set("lastname","Hunt");
            user.set("email","Brad.Hunt@learnosity.com");
            
            request.set("user",user);


            Init init = new Init("author", security, secret, request);
            ViewBag.SignedRequest = init.generate();
            return View();
        }

        public ActionResult Assess()
        {
            string sessionId=Uuid.generate();
            string userId= "Brad-Hunt-Demo-Student-User";

            JsonObject security = new JsonObject();
            security.set("consumer_key", consumerKey);
            security.set("domain", domain);

            JsonObject request = new JsonObject();
            request.set("name", "Exploring Planets");               //https://reference.learnosity.com/items-api/initialization/name
            request.set("activity_template_id", "demo-activity-1"); //https://reference.learnosity.com/items-api/initialization/activity_template_id
            request.set("user_id", userId);                         //https://reference.learnosity.com/items-api/initialization/user_id
            request.set("rendering_type", "assess");                //https://reference.learnosity.com/items-api/initialization/rendering_type
            request.set("type", "submit_practice");                 //https://reference.learnosity.com/items-api/initialization/type
            request.set("activity_id", "1stPeriodScience"); ;       //https://reference.learnosity.com/items-api/initialization/activity_id
            request.set("session_id",sessionId);                    //https://reference.learnosity.com/items-api/initialization/session_id


            //https://reference.learnosity.com/items-api/initialization/config.configuration.onsubmit_redirect_url
            JsonObject configuration = new JsonObject();
            configuration.set("onsubmit_redirect_url", String.Format("/Learnosity/Reports?sessionid={0}&userid={1}", sessionId,userId)); 

            JsonObject config = new JsonObject();
            config.set("configuration", configuration);

            request.set("config", config);
            
            Init init = new Init("items", security, secret, request);
            ViewBag.SignedRequest = init.generate();
            return View();
        }

        public ActionResult Reports()
        {
            // Get sessionid from the query string
            string sessionId = HttpContext.Request.Query["sessionid"].ToString();

            JsonObject security = new JsonObject();
            security.set("consumer_key", consumerKey);
            security.set("domain", domain);

            JsonObject request = new JsonObject();

            JsonObject report1= new JsonObject();
            report1.set("type", "session-detail-by-item");          //https://reference.learnosity.com/reports-api/reporttypes#sessionsDetailByItemReport
            report1.set("id", "session-detail");                    //https://reference.learnosity.com/reports-api/reporttypes#sessiondetailbyitem-id
            report1.set("user_id","Brad-Hunt-Demo-Student-User");   //https://reference.learnosity.com/reports-api/reporttypes#sessiondetailbyitem-user_id
            report1.set("session_id", sessionId);                   //https://reference.learnosity.com/reports-api/reporttypes#sessiondetailbyitem-session_id
          
            JsonObject reports = new JsonObject(true);              //https://reference.learnosity.com/reports-api/initialization/reports  (true here indicates array of reports)
            reports.set(report1);
      
            request.set("reports", reports);

            Init init = new Init("reports", security, secret, request);
            ViewBag.SignedRequest = init.generate();
            return View();
        }
    }
}



Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Learnosity/Activities.cshtml
    <h1>Activity Bank</h1>
    <div id="learnosity-author"></div>

    <script src="https://authorapi.learnosity.com/?v2024.1.LTS"></script>
    <script>
        var initializationObject = @Html.Raw(ViewBag.SignedRequest);
        
        var authorApp=LearnosityAuthor.init(initializationObject);
    </script>

Views/Learnosity/Assess.cshtml
    <div id="learnosity_assess"></div>
    <script src="https://items.learnosity.com/?v2024.1.LTS"></script>
    <script>
        var initializationObject = @Html.Raw(ViewBag.SignedRequest);
        
        var itemsApp=LearnosityItems.init(initializationObject);
        
    </script>

Views/Learnosity/Items.cshtml
    <h1>Item Bank</h1>
    <div id="learnosity-author"></div>

    <script src="https://authorapi.learnosity.com/?v2024.1.LTS"></script>
    <script>
        var initializationObject = @Html.Raw(ViewBag.SignedRequest);
        
        var authorApp=LearnosityAuthor.init(initializationObject);
    </script>

Views/Learnosity/Reports.cshtml
   <span class="learnosity-report" id="session-detail"></span>
    <script src="https://reports.learnosity.com/?v2024.1.LTS"></script>
    <script>
        var initializationObject = @Html.Raw(ViewBag.SignedRequest);
        LearnosityReports.init(initializationObject, {
            readyListener: function () {
                console.log('Reports API is ready!');
            }
        });
    </script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LearnosityDotNetExample</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LearnosityDotNetExample.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Learnosity</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Learnosity" asp-action="Items">Items</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Learnosity" asp-action="Activities">Activities</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Learnosity" asp-action="Assess">Assess</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LearnosityDotNetExample - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>